config/routes.rb
Rails.application.routes.draw do
  root to: 'blogs#index'
  resources 'blogs'
end

app/models/blog.rb
require 'rss'

class Blog < ActiveRecord::Base
  has_many :posts

  validates :author, uniqueness: true
  validates :rss_url, uniqueness: true

  before_save :format_rss_url
  before_save :format_url

  after_save :create_posts

  def create_posts
    rss = RSS::Parser.parse(rss_url, false)
    rss.items.each do |post|
      posts.create(
        title: post.title,
        url: post.link,
        published_on: post.pubDate
      )
    end
  end

  private

  def format_rss_url
    url_formatter = UrlFormatter.new(rss_url)
    self.rss_url = url_formatter.format_rss_url
  end

  def format_url
    url_formatter = UrlFormatter.new(rss_url)
    self.url = url_formatter.format_url
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :blog

  validates :title, uniqueness: true
  validates :url, uniqueness: true
end

app/models/url_formatter.rb
class UrlFormatter
  attr_reader :rss_url, :http_regex, :rss_regex, :medium_rss_regex, :http

  def initialize(rss_url)
    @rss_url = rss_url
    @http_regex = /^(http|https):\/\//
    @rss_regex = /.+(?=\/.*)/
    @medium_rss_regex = /.+\/feed\/.+/
    @http = "http://"
  end

  def format_rss_url
    remove_trailing_slash_if_present
    unless rss_url.match(http_regex)
      http + rss_url
    else
      rss_url
    end
  end

  def format_url
    case
    when rss_url.match(medium_rss_regex)
      rss_url.gsub("/feed", "")
    when !rss_url.match(http_regex)
      http + rss_url.match(rss_regex)
    else
      rss_url.match(rss_regex)
    end
  end

  private

  def remove_trailing_slash_if_present
    @rss_url[-1] = "" if rss_url.last == "/"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blog = Blog.new
    @posts = Post.order(published_on: :desc)
  end

  def create
    blog = Blog.new(blog_params)
    if blog.save
      flash[:notice] = "Added #{blog.rss_url}"
      redirect_to root_path
    else
      flash[:notice] = "Invalid request"
      redirect_to root_path
    end
  end

  private

  def blog_params
    params.require('blog').permit(:author, :rss_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blogs/index.html.erb
<div class="row col-md-6 col-md-offset-3 center">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash-#{name}" %>
  <% end %>
</div>

<div class="row col-md-6 col-md-offset-3 center">
  <div class='add-blog form-inline'>
    <%= form_for @blog, url: blogs_path  do |f| %>
      <%= f.text_field :author, placeholder: 'Your Name', class: "form-control" %>
      <%= f.text_field :rss_url, placeholder: "Your Blog's RSS URL", class: "form-control" %>
      <%= f.submit 'Add Your Blog!', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div>
  <div class="posts list-group table-responsive">
    <table class="table">
      <% @posts.each do |post| %>
        <tr class="row col-md-6 col-md-offset-3">
          <td><%= link_to post.title, post.url %></td>
          <td><%= link_to post.blog.author, post.blog.url %></td>
        </tr>
        <!-- <div class="row post col-md-6 col-md-offset-3 list-group-item"> -->
          <!-- <span class='float-right'> -->
            
          <!-- </span> -->
        <!-- </div> -->
      <% end %>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TuringBlogs</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= favicon_link_tag "turing_logo.ico" %>
    <link href='https://fonts.googleapis.com/css?family=Lato:400,300' rel='stylesheet' type='text/css'>
    <%= csrf_meta_tags %>

  </head>
  <body>
    <div class="container-fluid">
      <%= render 'partials/navbar' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/partials/_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="center">
    <%= image_tag 'turing_logo.png', width: 70 %>
    <h1>TURING BLOGS</h1>
  </div>
</div>